### ISSUE TITLE
Debug slice feature has confusing numbers

### ISSUE THREAD

**Issue by akrly** [ostat/vacuum-hose-adapter-openscad#11]
Hi,

When I set the "End2 Measurement" to outer the rendered number still displays the inner diameter value Arrows, text are fine. See attached screenshot.

![image](https://github.com/ostat/vacuum-hose-adapter-openscad/assets/40865147/27231800-52ad-4bb7-a940-d79f2a8bd649)

**Comment by lambtho12** [comment]
Sorry for offtopic, but how do you display the dimensions like that using openSCAD? Is there a library for it?

**Comment by akrly** [comment]
Hey, no worries. Unfortunately it's not openSCAD functionality.

You'll find a debug option at the bottom of the config parameters menu. It splits the model if you enable it.

**Comment by ostat** [comment]
> Sorry for offtopic, but how do you display the dimensions like that using openSCAD? Is there a library for it?

Its done creating standard openscad objects in the model. You can use the `$preview` flag to prevent them being included in the stl.
I use a modified version of the `UB.scad` library to create them. 
https://github.com/ostat/vacuum-hose-adapter-openscad/blob/main/modules/ub.scad

**Comment by ostat** [comment]
this is resolved
