### ISSUE TITLE
Cen-Tec Hose-side Connector

### ISSUE THREAD

**Issue by vifino** [ostat/vacuum-hose-adapter-openscad#12]
Hey, these adapters seem a lot higher quality than the models I found and happen to appear just at the right moment. Good job!

I would love to see the hose-side (with the clips) Cen-Tec connectors as well!
This would allow connecting to equipment that already uses such a connector, obviously.

Bosch's Click and Clean seems to use the same Cen-Tec style connectors, so it'd be useful for Bosch saws and such as well.

**Comment by ostat** [comment]
> I would love to see the hose-side (with the clips) Cen-Tec connectors as well! This would allow connecting to equipment that already uses such a connector, obviously.
> Bosch's Click and Clean seems to use the same Cen-Tec style connectors, so it'd be useful for Bosch saws and such as well.

Hi, I think that was fixed in this updated a984a4a
Let me know if I misunderstood.
![image](https://github.com/ostat/vacuum-hose-adapter-openscad/assets/2128234/31ed266d-f910-4baa-a382-b5457cdbe82d)

**Comment by vifino** [comment]
Hey! The lower connector does indeed look like the hose side connector (Male?), but how do you get that one?

I would like a "Connector 1 - CenTec" option group that allows you to switch between Male/Hose Sleeve and the existing Female/Tool Side socket.
Centec seems to use Male/Female in the few places where they name it.

**Comment by ostat** [comment]
Oh I misunderstood. 
I have not modelled the male side of the Centec style connector. Only the female side. 
I could try model it at some stage. It does not look that complex. Happy for submissions also :).

**Comment by ostat** [comment]
I had a crack at the adapter, I have not tested this :) 
changeset dd23c9c

![image](https://github.com/ostat/vacuum-hose-adapter-openscad/assets/2128234/e93f5b57-c77c-49e2-9432-fbfcd085aaf0)
![image](https://github.com/ostat/vacuum-hose-adapter-openscad/assets/2128234/b485afd8-8151-481b-8d99-d1fff4539593)

**Comment by ostat** [comment]
I believe this is good now, so will close this issue. Please re-open or create new ticket if you think the adapter needs updating
