### ISSUE TITLE
suggestion: add reference to dotSCAD in readme

### ISSUE THREAD

**Issue by kitlaan** [ostat/vacuum-hose-adapter-openscad#5]
It was pretty obvious given the error messages... But it would be useful to have an up-front statement of the dependency on https://github.com/JustinSDK/dotSCAD

**Comment by ostat** [comment]
I agree, I should have done this. 
Locally I have extracted the parts of dotSCAD we are using and checked it in as an included file, so this will no longer be needed. I just need to finish some cleanup I was doing.

**Comment by ostat** [comment]
I have added dotSCD (well a cutdown version) to the checked in files.
Sorry for the delay
