### ISSUE TITLE
Support CenTec adapter

### ISSUE THREAD

**Issue by ostat** [ostat/vacuum-hose-adapter-openscad#7]
Add support for CenTec connector system

**Comment by landrypm** [comment]
(Also messaged you on Printables.)

I printed two couplers last night and the fit is very good. Here is a link to a Google Photos album with a few pictures and one short video using the test coupler. I also printed one other and the size was perfect but the holes for the retaining clips were not working as well. I did not use supports and I think the "top" of the holes were not square and that is allowing the clip to slip out on one side. I will reprint with supports in the holes to confirm.

https://photos.app.goo.gl/H1gDvLU8k3u3sgJF9

It seemed that the fit to the printed coupler was equivalent to the fit with the commercial bought ones I have. As soon as I get a real coupler printed that I can use to connect to a tool I will be able to check for air loss. But I don't anticipate it to be any worse than with the commercial couplers.

Thanks so much for your time and talent. Let me know there is some way I can buy you a beer or lunch.

**Comment by ostat** [comment]
thanks for the feedback, and detailed video.

I made some tweaks, that might help.

- Changed the pin hole corner radius from 1mm to 3mm 
- Change the pin hole hole width from 11mm to 9.5
- Changed how the taper to the pin hole. Start is the same but end is almost flush. Should help prevent slipping out.
- Changed internal length from 25mm to 24mm
- Change internal radius from 22.67 to 22.3
- If we can make it fit snug, I think the pin will not fall out as easily.
![Screenshot 2024-03-08 113317](https://github.com/ostat/vacuum-hose-adapter-openscad/assets/2128234/eb201bd5-1d8f-488f-9122-a990acebc191)

[centec-test-print_V2.zip](https://github.com/ostat/vacuum-hose-adapter-openscad/files/14535484/centec-test-print_V2.zip)
